# Generated by Django 3.1.3 on 2020-12-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curr_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr1', models.CharField(max_length=100)),
                ('curr2', models.CharField(max_length=100)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
